#!/bin/sh

TMPDIR=

doexit()
{
	if [ ! "$TMPDIR" = "" ]; then
		sudo rm -rf $TMPDIR
	fi
	exit $1
}

usage()
{
	echo "$0 <app name> <package path> <version> <build> <package architecture> <lib dir> <32-bit lib dir> <bin dir> <32-bit bin dir>"
	exit 1
}

ARCH=`uname -m`
if [ "$1" = "" ]; then usage $0; fi
APPNAME=$1
if [ "$2" = "" ]; then usage $0; fi
PKGNAME=$2
if [ "$3" = "" ]; then usage $0; fi
VERSION=$3
if [ "$4" = "" ]; then usage $0; fi
BUILD=$4
if [ "$5" = "" ]; then usage $0; fi
DEBARCH=$5
if [ "$6" = "" ]; then usage $0; fi
LDIR=$6
if [ "$7" = "" ]; then usage $0; fi
LDIR32=$7
if [ "$8" = "" ]; then usage $0; fi
EDIR=$8
if [ "$9" = "" ]; then usage $0; fi
EDIR32=$9

rm -f $PKGNAME
umask 022
TMPDIR=`mktemp -d /tmp/vglbuild.XXXXXX || doexit -1`
mkdir $TMPDIR/DEBIAN || doexit -1
(cat deb-control.tmpl | sed s/{__PKGNAME}/$APPNAME/g | sed s/{__VERSION}/$VERSION/g | sed s/{__BUILD}/$BUILD/g | sed s/{__ARCH}/$DEBARCH/g > $TMPDIR/DEBIAN/control) || doexit -1

mkdir -p $TMPDIR/usr/bin || doexit -1
mkdir -p $TMPDIR/usr/lib || doexit -1
if [ "$DEBARCH" = "amd64" ]; then
	mkdir -p $TMPDIR/usr/lib32 || doexit -1
fi
mkdir -p $TMPDIR/opt/$APPNAME/bin || doexit -1
mkdir -p $TMPDIR/opt/$APPNAME/fakelib || doexit -1
if [ "$DEBARCH" = "amd64" ]; then
	mkdir -p $TMPDIR/opt/$APPNAME/fakelib/64 || doexit -1
	ln -fs /opt/$APPNAME/fakelib/64 $TMPDIR/opt/$APPNAME/lib64 || doexit -1
fi
install -m 755 $EDIR32/vglclient $TMPDIR/usr/bin/ || doexit -1
install -m 755 $EDIR32/vglconfig $TMPDIR/usr/bin/ || doexit -1
install -m 755 $EDIR32/vglconnect $TMPDIR/usr/bin/ || doexit -1
install -m 755 $EDIR32/vgllogin $TMPDIR/usr/bin/ || doexit -1
install -m 755 $EDIR32/vglrun $TMPDIR/usr/bin/ || doexit -1
install -m 755 rr/vglgenkey $TMPDIR/usr/bin/ || doexit -1
install -m 755 rr/vglserver_config $TMPDIR/usr/bin/ || doexit -1
install -m 755 $EDIR32/tcbench $TMPDIR/opt/$APPNAME/bin/ || doexit -1
install -m 755 $EDIR32/nettest $TMPDIR/opt/$APPNAME/bin/ || doexit -1
install -m 755 $EDIR32/cpustat $TMPDIR/opt/$APPNAME/bin/ || doexit -1
install -m 755 $EDIR32/glxinfo $TMPDIR/opt/$APPNAME/bin/ || doexit -1
install -m 755 $EDIR32/glxspheres $TMPDIR/opt/$APPNAME/bin/ || doexit -1
install -m 755 $LDIR/librrfaker.so $TMPDIR/usr/lib/ || doexit -1
install -m 755 $LDIR/libdlfaker.so $TMPDIR/usr/lib/ || doexit -1
install -m 755 $LDIR/libgefaker.so $TMPDIR/usr/lib/ || doexit -1
if [ "$DEBARCH" = "amd64" ]; then
	install -m 755 $LDIR32/librrfaker.so $TMPDIR/usr/lib32/ || doexit -1
	install -m 755 $LDIR32/libdlfaker.so $TMPDIR/usr/lib32/ || doexit -1
	install -m 755 $LDIR32/libgefaker.so $TMPDIR/usr/lib32/ || doexit -1
	install -m 755 $EDIR/glxspheres $TMPDIR/opt/$APPNAME/bin/glxspheres64 || doexit -1
	install -m 755 $EDIR/vglconfig64 $TMPDIR/usr/bin/ || doexit -1
	ln -fs /usr/lib/librrfaker.so $TMPDIR/opt/$APPNAME/fakelib/64/libGL.so || doexit -1
	ln -fs /usr/bin/vglconfig64 $TMPDIR/opt/$APPNAME/bin/vglconfig64 || doexit -1
	ln -fs /usr/lib32/librrfaker.so $TMPDIR/opt/$APPNAME/fakelib/libGL.so || doexit -1
else
	ln -fs /usr/lib/librrfaker.so $TMPDIR/opt/$APPNAME/fakelib/libGL.so || doexit -1
fi
ln -fs /usr/bin/vglclient $TMPDIR/opt/$APPNAME/bin/vglclient || doexit -1
ln -fs /usr/bin/vglconfig $TMPDIR/opt/$APPNAME/bin/vglconfig || doexit -1
ln -fs /usr/bin/vglconnect $TMPDIR/opt/$APPNAME/bin/vglconnect || doexit -1
ln -fs /usr/bin/vglgenkey $TMPDIR/opt/$APPNAME/bin/vglgenkey || doexit -1
ln -fs /usr/bin/vgllogin $TMPDIR/opt/$APPNAME/bin/vgllogin || doexit -1
ln -fs /usr/bin/vglserver_config $TMPDIR/opt/$APPNAME/bin/vglserver_config || doexit -1
ln -fs /usr/bin/vglrun $TMPDIR/opt/$APPNAME/bin/vglrun || doexit -1
ln -fs /opt/$APPNAME/fakelib $TMPDIR/opt/$APPNAME/lib || doexit -1
ln -fs /usr/share/doc/$APPNAME-$VERSION $TMPDIR/opt/$APPNAME/doc || doexit -1
mkdir -p $TMPDIR/usr/share/doc/$APPNAME-$VERSION || doexit -1
install -m 644 fltk/COPYING $TMPDIR/usr/share/doc/$APPNAME-$VERSION/LICENSE-FLTK.txt || doexit -1
install -m 644 putty/LICENCE $TMPDIR/usr/share/doc/$APPNAME-$VERSION/LICENSE-PuTTY.txt || doexit -1
install -m 644 x11windows/xauth.license $TMPDIR/usr/share/doc/$APPNAME-$VERSION/LICENSE-xauth.txt || doexit -1
install -m 644 LGPL.txt $TMPDIR/usr/share/doc/$APPNAME-$VERSION/ || doexit -1
install -m 644 LICENSE.txt $TMPDIR/usr/share/doc/$APPNAME-$VERSION/ || doexit -1
install -m 644 LICENSE-OpenSSL.txt $TMPDIR/usr/share/doc/$APPNAME-$VERSION/ || doexit -1
install -m 644 ChangeLog.txt $TMPDIR/usr/share/doc/$APPNAME-$VERSION/ || doexit -1
install -m 644 doc/index.html $TMPDIR/usr/share/doc/$APPNAME-$VERSION/ || doexit -1
install -m 644 doc/*.png $TMPDIR/usr/share/doc/$APPNAME-$VERSION/ || doexit -1
install -m 644 doc/*.gif $TMPDIR/usr/share/doc/$APPNAME-$VERSION/ || doexit -1
install -m 644 doc/*.css $TMPDIR/usr/share/doc/$APPNAME-$VERSION/ || doexit -1

sudo chown -R root:root $TMPDIR/* || doexit -1
dpkg -b $TMPDIR $PKGNAME || doexit -1
doexit 0
