#!/bin/sh

usage()
{
	echo "$0 <app name> <JPEG library type> <build dir.> <version> <build> <lib dir> <bin dir> <Open mediaLib lib dir>"
	exit 1
}

if [ "$1" = "" ]; then usage $0; fi
APPNAME=$1
if [ "$2" = "" ]; then usage $0; fi
JPEGLIB=$2
if [ "$3" = "" ]; then usage $0; fi
BLDDIR=$3
if [ "$4" = "" ]; then usage $0; fi
VERSION=$4
if [ "$5" = "" ]; then usage $0; fi
BUILD=$5
if [ "$6" = "" ]; then usage $0; fi
EDIR=$6
if [ "$JPEGLIB" = "medialib" ]; then
	if [ "$7" = "" ]; then usage $0; fi
	OMLDIR=$7
fi

PACKAGEMAKER=/Developer/Applications/Utilities/PackageMaker.app/Contents/MacOS/PackageMaker

umask 022
TMPDIR=`mktemp -d /tmp/vglbuild.XXXXXX`
__PWD=`pwd`; \
mkdir -p $TMPDIR/pkg/usr/bin || exit -1
mkdir -p $TMPDIR/pkg/opt/VirtualGL/bin || exit -1
mkdir -p $TMPDIR/pkg/usr/share/doc/$APPNAME-$VERSION || exit -1
install -m 755 $EDIR/vglclient.exe $TMPDIR/pkg/usr/bin/ || exit -1
install -m 755 $EDIR/vglconnect $TMPDIR/pkg/usr/bin/ || exit -1
ln -fs /usr/bin/vglclient.exe $TMPDIR/pkg/opt/$APPNAME/bin/ || exit -1
ln -fs /usr/bin/vglconnect $TMPDIR/pkg/opt/$APPNAME/bin/ || exit -1
install -m 755 $EDIR/tcbench.exe $TMPDIR/pkg/opt/$APPNAME/bin/ || exit -1
install -m 755 $EDIR/nettest.exe $TMPDIR/pkg/opt/$APPNAME/bin/ || exit -1
install -m 755 $EDIR/glxinfo.exe $TMPDIR/pkg/opt/$APPNAME/bin/ || exit -1
install -m 755 $EDIR/glxspheres.exe $TMPDIR/pkg/opt/$APPNAME/bin/ || exit -1
install -m 644 LGPL.txt $TMPDIR/pkg/usr/share/doc/$APPNAME-$VERSION/ || exit -1
install -m 644 fltk/COPYING $TMPDIR/pkg/usr/share/doc/$APPNAME-$VERSION/LICENSE-FLTK.txt || exit -1
install -m 644 putty/LICENCE $TMPDIR/pkg/usr/share/doc/$APPNAME-$VERSION/LICENSE-PuTTY.txt || exit -1
install -m 644 x11windows/xauth.license $TMPDIR/pkg/usr/share/doc/$APPNAME-$VERSION/LICENSE-xauth.txt || exit -1
install -m 644 LICENSE.txt $TMPDIR/pkg/usr/share/doc/$APPNAME-$VERSION/ || exit -1
install -m 644 ChangeLog.txt $TMPDIR/pkg/usr/share/doc/$APPNAME-$VERSION/ || exit -1
install -m 644 doc/index.html $TMPDIR/pkg/usr/share/doc/$APPNAME-$VERSION/ || exit -1
install -m 644 doc/*.gif $TMPDIR/pkg/usr/share/doc/$APPNAME-$VERSION/ || exit -1
install -m 644 doc/*.png $TMPDIR/pkg/usr/share/doc/$APPNAME-$VERSION/ || exit -1
install -m 644 doc/*.css $TMPDIR/pkg/usr/share/doc/$APPNAME-$VERSION/ || exit -1
if [ "$JPEGLIB" = "medialib" ]; then
	install -m 644 $OMLDIR/openmliblite.dll $TMPDIR/pkg/usr/bin/ || exit -1
fi
cd $TMPDIR/pkg
tar cfj ../$APPNAME-$VERSION-$BUILD.tar.bz2 * || exit -1
cd $__PWD
mv $TMPDIR/*.tar.bz2 $BLDDIR || exit -1
rm -rf $TMPDIR
