#!/bin/sh

usage()
{
	echo "$0 <app name> <JPEG library type> <build dir.> <version> <build> <lib dir> <bin dir>"
	exit 1
}

TMPDIR=

doexit()
{
	if [ ! "$TMPDIR" = "" ]; then
		sudo rm -rf $TMPDIR
	fi
	exit $1
}

if [ "$1" = "" ]; then usage $0; fi
APPNAME=$1
if [ "$2" = "" ]; then usage $0; fi
JPEGLIB=$2
if [ "$3" = "" ]; then usage $0; fi
BLDDIR=$3
if [ "$4" = "" ]; then usage $0; fi
VERSION=$4
if [ "$5" = "" ]; then usage $0; fi
BUILD=$5
if [ "$6" = "" ]; then usage $0; fi
EDIR=$6

PACKAGEMAKER=/Developer/Applications/Utilities/PackageMaker.app/Contents/MacOS/PackageMaker

if [ -f $BLDDIR/$APPNAME.dmg ]; then
	rm -f $BLDDIR/$APPNAME.dmg
fi
umask 022
TMPDIR=`mktemp -d /tmp/vglbuild.XXXXXX || doexit -1`
mkdir -p $TMPDIR/pkg/Package_Root/usr/bin || doexit -1
mkdir -p $TMPDIR/pkg/Package_Root/opt/$APPNAME/bin || doexit -1
mkdir -p $TMPDIR/pkg/Package_Root/opt/$APPNAME/lib || doexit -1
mkdir -p $TMPDIR/pkg/Package_Root/Library/Documentation/$APPNAME || doexit -1
chmod 1775 $TMPDIR/pkg/Package_Root/Library || doexit -1
chmod 775 $TMPDIR/pkg/Package_Root/Library/Documentation || doexit -1
mkdir -p "$TMPDIR/pkg/Package_Root/Applications/$APPNAME" || doexit -1
chmod 775 $TMPDIR/pkg/Package_Root/Applications || doexit -1
mkdir -p $TMPDIR/pkg/Resources || doexit -1
(cat Description.plist.tmpl | sed s/{__VERSION}/$VERSION/g	| sed s/{__APPNAME}/$APPNAME/g > $TMPDIR/pkg/Description.plist) || doexit -1
(cat Info.plist.tmpl | sed s/{__VERSION}/$VERSION/g	| sed s/{__BUILD}/$BUILD/g > $TMPDIR/pkg/Info.plist) || doexit -1
install -m 755 $EDIR/vglclient $TMPDIR/pkg/Package_Root/usr/bin || doexit -1
install -m 755 $EDIR/vglconnect $TMPDIR/pkg/Package_Root/usr/bin || doexit -1
install -m 755 $EDIR/tcbench $TMPDIR/pkg/Package_Root/opt/$APPNAME/bin || doexit -1
install -m 755 $EDIR/nettest $TMPDIR/pkg/Package_Root/opt/$APPNAME/bin || doexit -1
install -m 755 $EDIR/glxinfo $TMPDIR/pkg/Package_Root/opt/$APPNAME/bin || doexit -1
(cat uninstall.sh.tmpl | sed s/{__APPNAME}/$APPNAME/g > $TMPDIR/pkg/Package_Root/opt/$APPNAME/bin/uninstall) || doexit -1
chmod 755 $TMPDIR/pkg/Package_Root/opt/$APPNAME/bin/uninstall
ln -fs /usr/bin/vglclient $TMPDIR/pkg/Package_Root/opt/$APPNAME/bin/vglclient || doexit -1
ln -fs /usr/bin/vglconnect $TMPDIR/pkg/Package_Root/opt/$APPNAME/bin/vglconnect || doexit -1
if [ "$JPEGLIB" = "ipp" ]; then
	install -m 755 /usr/lib/libturbojpeg.dylib $TMPDIR/pkg/Package_Root/opt/$APPNAME/lib || doexit -1
	install_name_tool -change libturbojpeg.dylib /opt/$APPNAME/lib/libturbojpeg.dylib $TMPDIR/pkg/Package_Root/usr/bin/vglclient || doexit -1
fi
install -m 644 fltk/COPYING $TMPDIR/pkg/Package_Root/Library/Documentation/$APPNAME/LICENSE-FLTK.txt || doexit -1
install -m 644 putty/LICENCE $TMPDIR/pkg/Package_Root/Library/Documentation/$APPNAME/LICENSE-PuTTY.txt || doexit -1
install -m 644 x11windows/xauth.license $TMPDIR/pkg/Package_Root/Library/Documentation/$APPNAME/LICENSE-xauth.txt || doexit -1
install -m 644 LGPL.txt LICENSE.txt ChangeLog.txt doc/index.html doc/*.png doc/*.gif doc/*.css $TMPDIR/pkg/Package_Root/Library/Documentation/$APPNAME || doexit -1
install -m 644 ReadMe-MacApp.txt "$TMPDIR/pkg/Package_Root/Applications/$APPNAME/Read Me.txt" || doexit -1
sudo ln -fs /Library/Documentation/$APPNAME/index.html "$TMPDIR/pkg/Package_Root/Applications/$APPNAME/User's Guide.html" || doexit -1
sudo chown -R root:admin $TMPDIR/pkg/Package_Root || doexit -1
sudo chown root:0 $TMPDIR/pkg/Package_Root/usr || doexit -1
sudo chown root:0 $TMPDIR/pkg/Package_Root/usr/bin || doexit -1
cp License.rtf Welcome.rtf ReadMe.rtf $TMPDIR/pkg/Resources/ || doexit -1
mkdir $TMPDIR/dmg
$PACKAGEMAKER -build -v -p $TMPDIR/dmg/$APPNAME.pkg \
	-f $TMPDIR/pkg/Package_Root -r $TMPDIR/pkg/Resources \
	-i $TMPDIR/pkg/Info.plist -d $TMPDIR/pkg/Description.plist || doexit -1
install -m 644 vgluninstall.applescript $TMPDIR || doexit -1
sudo osacompile -t APPL -o "$TMPDIR/dmg/Uninstall $APPNAME.app" $TMPDIR/vgluninstall.applescript || doexit -1
sudo chown -R $USER "$TMPDIR/dmg/Uninstall $APPNAME.app" || doexit -1
hdiutil create -fs HFS+ -volname $APPNAME-$VERSION \
	-srcfolder "$TMPDIR/dmg" \
	$TMPDIR/$APPNAME.dmg || doexit -1
cp $TMPDIR/$APPNAME.dmg $BLDDIR || doexit -1
doexit 0
