#!/bin/sh
_installdir=$1
_platform=$2
_subplatform=$3
if [ "$_platform" = "solaris" -a "$_subplatform" = "64" ]; then
LIB64=sparcv9
fi
if [ "$_platform" = "solx86" -a "$_subplatform" = "64" ]; then
LIB64=amd64
fi
echo i copyright
echo i depend
echo i pkginfo
echo d none VirtualGL 0755 root bin
echo d none VirtualGL/bin 0755 root bin
echo f none VirtualGL/bin/vglclient 0755 root bin
echo f none VirtualGL/bin/vglconfig 0755 root bin
echo f none VirtualGL/bin/vglconnect 0755 root bin
echo f none VirtualGL/bin/vgllogin 0755 root bin
echo f none VirtualGL/bin/vglrun 0755 root bin
echo f none VirtualGL/bin/vglgenkey 0755 root bin
echo f none VirtualGL/bin/vglserver_config 0755 root bin
echo f none VirtualGL/bin/tcbench 0755 root bin
echo f none VirtualGL/bin/nettest 0755 root bin
echo f none VirtualGL/bin/glxinfo 0755 root bin
echo f none VirtualGL/bin/glxspheres 0755 root bin
if [ "$_subplatform" = "64" ]; then
echo f none VirtualGL/bin/glxspheres64 0755 root bin
fi
echo d none VirtualGL/fakelib 0755 root bin
echo s none VirtualGL/fakelib/libGL.so=../lib/librrfaker.so
if [ "$_subplatform" = "64" ]; then
echo d none VirtualGL/fakelib/$LIB64 0755 root bin
echo s none VirtualGL/fakelib/$LIB64/libGL.so=../../lib/$LIB64/librrfaker.so
echo s none VirtualGL/fakelib/64=$LIB64
fi
echo d none VirtualGL/include 0755 root bin
echo f none VirtualGL/include/rrtransport.h 0644 root bin
echo f none VirtualGL/include/rr.h 0644 root bin
echo d none VirtualGL/lib 0755 root bin
echo f none VirtualGL/lib/librrfaker.so 0755 root bin
echo f none VirtualGL/lib/libdlfaker.so 0755 root bin
echo f none VirtualGL/lib/libgefaker.so 0755 root bin
if [ "$_subplatform" = "64" ]; then
echo d none VirtualGL/lib/$LIB64 0755 root bin
echo f none VirtualGL/lib/$LIB64/librrfaker.so 0755 root bin
echo f none VirtualGL/lib/$LIB64/libdlfaker.so 0755 root bin
echo f none VirtualGL/lib/$LIB64/libgefaker.so 0755 root bin
echo s none VirtualGL/lib/64=$LIB64
fi
echo d none VirtualGL/doc 0755 root bin
echo f none VirtualGL/doc/LGPL.txt 0644 root bin
echo f none VirtualGL/doc/LICENSE.txt 0644 root bin
echo f none VirtualGL/doc/LICENSE-FLTK.txt 0644 root bin
echo f none VirtualGL/doc/LICENSE-PuTTY.txt 0644 root bin
echo f none VirtualGL/doc/LICENSE-xauth.txt 0644 root bin
echo f none VirtualGL/doc/ChangeLog.txt 0644 root bin
for i in doc/*.gif; do echo f none VirtualGL/$i 0644 root bin; done
echo f none VirtualGL/doc/index.html 0644 root bin
for i in doc/*.png; do echo f none VirtualGL/$i 0644 root bin; done
for i in doc/*.css; do echo f none VirtualGL/$i 0644 root bin; done
echo d none VirtualGL/doc 0755 root bin
