#!/bin/sh

set -u
set -e
trap onexit INT
trap onexit TERM
trap onexit EXIT

TMPDIR=

onexit()
{
	if [ ! "$TMPDIR" = "" ]; then
		sudo rm -rf $TMPDIR
	fi
}

usage()
{
	echo "$0 <app name> <package path> <version> <build> <package architecture> <lib dir> <32-bit lib dir> <bin dir> <32-bit bin dir>"
	exit 1
}

if [ $# -lt 9 ]; then usage $0; fi
ARCH=`uname -m`
APPNAME=$1
PKGNAME=$2
VERSION=$3
BUILD=$4
DEBARCH=$5
LDIR=$6
LDIR32=$7
EDIR=$8
EDIR32=$9

rm -f $PKGNAME
umask 022
TMPDIR=`mktemp -d /tmp/vglbuild.XXXXXX`
mkdir $TMPDIR/DEBIAN
cat deb-control.tmpl | sed s/{__PKGNAME}/$APPNAME/g | sed s/{__VERSION}/$VERSION/g | sed s/{__BUILD}/$BUILD/g | sed s/{__ARCH}/$DEBARCH/g > $TMPDIR/DEBIAN/control

make install prefix=$TMPDIR/usr

mkdir -p $TMPDIR/opt/$APPNAME/bin
for i in tcbench nettest cpustat glxinfo glxspheres; do
	mv $TMPDIR/usr/bin/$i $TMPDIR/opt/$APPNAME/bin/
done
if [ "$DEBARCH" = "amd64" ]; then
	mv $TMPDIR/usr/bin/glxspheres64 $TMPDIR/opt/$APPNAME/bin/
fi
pushd $TMPDIR/usr/bin
for i in *; do ln -fs /usr/bin/$i $TMPDIR/opt/$APPNAME/bin/; done
popd

if [ "$DEBARCH" = "amd64" ]; then
	mv $TMPDIR/usr/lib $TMPDIR/usr/lib32
	mv $TMPDIR/usr/lib64 $TMPDIR/usr/lib
fi

rm -rf $TMPDIR/usr/fakelib
mkdir -p $TMPDIR/opt/$APPNAME/fakelib
if [ "$DEBARCH" = "amd64" ]; then
	mkdir -p $TMPDIR/opt/$APPNAME/fakelib/64
fi
if [ "$DEBARCH" = "amd64" ]; then
	ln -fs /usr/lib32/librrfaker.so $TMPDIR/opt/$APPNAME/fakelib/libGL.so
	ln -fs /usr/lib/librrfaker.so $TMPDIR/opt/$APPNAME/fakelib/64/libGL.so
else
	ln -fs /usr/lib/librrfaker.so $TMPDIR/opt/$APPNAME/fakelib/libGL.so
fi

mkdir -p $TMPDIR/opt/$APPNAME/include
ln -fs /usr/include/rrtransport.h $TMPDIR/opt/$APPNAME/include/rrtransport.h
ln -fs /usr/include/rr.h $TMPDIR/opt/$APPNAME/include/rr.h

rm -rf $TMPDIR/usr/doc
ln -fs /usr/share/doc/$APPNAME-$VERSION $TMPDIR/opt/$APPNAME/doc
mkdir -p $TMPDIR/usr/share/doc/$APPNAME-$VERSION
install -m 644 fltk/COPYING $TMPDIR/usr/share/doc/$APPNAME-$VERSION/LICENSE-FLTK.txt
install -m 644 putty/LICENCE $TMPDIR/usr/share/doc/$APPNAME-$VERSION/LICENSE-PuTTY.txt
install -m 644 x11windows/xauth.license $TMPDIR/usr/share/doc/$APPNAME-$VERSION/LICENSE-xauth.txt
install -m 644 LGPL.txt $TMPDIR/usr/share/doc/$APPNAME-$VERSION/
install -m 644 LICENSE.txt $TMPDIR/usr/share/doc/$APPNAME-$VERSION/
install -m 644 ChangeLog.txt $TMPDIR/usr/share/doc/$APPNAME-$VERSION/
install -m 644 doc/index.html $TMPDIR/usr/share/doc/$APPNAME-$VERSION/
install -m 644 doc/*.png $TMPDIR/usr/share/doc/$APPNAME-$VERSION/
install -m 644 doc/*.gif $TMPDIR/usr/share/doc/$APPNAME-$VERSION/
install -m 644 doc/*.css $TMPDIR/usr/share/doc/$APPNAME-$VERSION/

sudo chown -Rh root:root $TMPDIR/*
dpkg -b $TMPDIR $PKGNAME

exit 0
