#!/bin/sh

# This script sanity checks the build environment for compiling 32-bit
# VirtualGL on an x86-64 Linux system.

RETVAL=0

if [ "$1" == "-fix" ]; then
	_FIX=1
fi

if [ -f /usr/include/openssl/opensslconf-x86_64.h ]; then
	if [ ! -f /usr/include/openssl/opensslconf-i386.h ]; then
		if [ $_FIX ]; then
			_PWD=`pwd`
			cd /usr/include/openssl
			ln -fs opensslconf-x86_64.h opensslconf-i386.h
			cd $_PWD
		else
			echo
			echo "ERROR: /usr/include/openssl/opensslconf-i386.h does not exist.  As root,"
			echo "  cd /usr/include/openssl"
			echo "  ln -fs opensslconf-x86_64.h opensslconf-i386.h"
			echo "or (also as root) rerun sanitycheck64 with an argument of -fix"
			echo "to fix this issue."
			echo
			RETVAL=1
		fi
	fi
fi

_LIBSSL=`find /lib/libssl.so.? 2>/dev/null | xargs | awk '{print $NF}'`
if [ -z "$_LIBSSL" ]; then
	_LIBSSL=`find /usr/lib/libssl.so.? 2>/dev/null | xargs | awk '{print $NF}'`
fi
_LIBCRYPTO=`find /lib/libcrypto.so.? 2>/dev/null | xargs | awk '{print $NF}'`
if [ -z "$_LIBCRYPTO" ]; then
	_LIBCRYPTO=`find /usr/lib/libcrypto.so.? 2>/dev/null | xargs | awk '{print $NF}'`
fi

if [ -z "$_LIBSSL" -o -z "$_LIBCRYPTO" ]; then
	echo
	echo "ERROR: 32-bit OpenSSL libraries are not installed.  These are"
	echo "usually contained in the openssl iX86 package, which should be"
	echo "available on your Linux distribution's install CD."
	echo
	RETVAL=1
else
	if [ ! -f /usr/lib/libssl.so -o ! -f /usr/lib/libcrypto.so ]; then
		if [ $_FIX ]; then
			_PWD=`pwd`
			cd /usr/lib
			ln -fs $_LIBSSL libssl.so
			ln -fs $_LIBCRYPTO libcrypto.so
			cd $_PWD
		else
			echo
			echo "ERROR: 32-bit OpenSSL library stubs do not exist.  As root,"
			echo "  cd /usr/lib"
			echo "  ln -fs" $_LIBSSL "libssl.so"
			echo "  ln -fs" $_LIBCRYPTO "libcrypto.so"
			echo "or (also as root) rerun sanitycheck64 with an argument of -fix"
			echo "to fix this issue."
			echo
			RETVAL=1
		fi
	fi
fi

exit $RETVAL
