all: rrglxgears

clean:
	rm -f rrglxgears rrglxgears.o

CFLAGS = -O

CINCLUDES = -I../../include -I/opt/SUNWvgl/include

LDFLAGS = -L../../lib -R../../lib \
	-L/opt/SUNWvgl/lib -R/opt/SUNWvgl/lib

rrglxgears.o: rrglxgears.c
	$(CC) $(CFLAGS) $(CINCLUDES) -c -o $@ $^

rrglxgears: rrglxgears.o
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $^ -lGL -lX11 -lXext -lm -lrr
