all: rrglxgears

clean:
	rm -f rrglxgears rrglxgears.o

CFLAGS = -m32 -O2 -I../../include -I../include -I/opt/VirtualGL/include

LDFLAGS = -m32 -L/usr/X11R6/lib -L../../lib -Xlinker -rpath -Xlinker ../../lib

rrglxgears.o: rrglxgears.c
	$(CC) $(CFLAGS) -c -o $@ $^

rrglxgears: rrglxgears.o
	$(CC) $(LDFLAGS) -o $@ $^ -lGL -lX11 -lXext -lm -lrr
