all: rrglxgears

clean:
	rm -f rrglxgears rrglxgears.o

CFLAGS = -O2 -I../../../include -I../include -I/opt/VirtualGL/include

LDFLAGS = -L/usr/X11R6/lib -L../../../lib -Xlinker -rpath -Xlinker ../../../lib

rrglxgears.o: rrglxgears.c
	$(CC) $(CFLAGS) -c -o $@ $^

rrglxgears: rrglxgears.o
	$(CC) $(LDFLAGS) -o $@ $^ -lGL -lX11 -lXext -lm -lrr
