#!/bin/sh
GEOPROBE_USEGLX=1
export GEOPROBE_USEGLX
PROMAGIC_USEGLX=1
export PROMAGIC_USEGLX

case `uname -s` in

Linux)

LD_PRELOAD=librrfaker.so:libGL.so.1 ${1+"$@"}

;;

IRIX*)

_RLD_LIST=librrfaker.so:libGL.so:libC.so:libpthread.so:DEFAULT ${1+"$@"}

;;

SunOS)

LD_PRELOAD=librrfaker.so:libGL.so ${1+"$@"}

;;

esac
