#!/bin/sh

usage()
{
	echo
	echo "Usage: `basename $0` [options] [--] <OpenGL app> [OpenGL app arguments]"
	echo
	echo "VirtualGL display options"
	echo "  +/-spoil    : Turn on/off frame spoiling"
	echo "  -d <d>      : set the display or GLP device on which 3D rendering is done"
	echo "  -client <d> : set the client display"
	echo "  +/-sync     : Enable/disable strict 2D/3D synchronization"
	echo "  +/-g        : Enable/disable gamma correction for Solaris clients"
	echo
	echo "VirtualGL network options"
	echo "  +/-s        : Enable/disable use of SSL"
	echo "  -p <p>      : TCP port to use when connecting to client"
	echo
	echo "VirtualGL compression options"
	echo "  -c <c>      : specify compression type (0=none, 1=motion JPEG)"
	echo "  -q <q>      : specify a JPEG quality value in the range [1-100]"
	echo "  -samp <s>   : specify JPEG YCbCr subsampling (444, 422, 411)"
	echo "  -np <n>     : Number of CPUs to use for compression"
	echo
	echo "VirtualGL miscellaneous options"
	echo "  +/-profile  : Enable/disable performance profiling"
	echo "  -64         : (Solaris only) Preload VirtualGL only into 64-bit apps"
	echo "  -32         : (Solaris only) Preload VirtualGL only into 32-bit apps"
	exit $1
}

GEOPROBE_USEGLX=1
export GEOPROBE_USEGLX
PROMAGIC_USEGLX=1
export PROMAGIC_USEGLX

if [ $# -eq 0 ]
then
	usage 0
fi
while [ $# -gt 0 ]
do
	case "$1" in
	+sy*)       VGL_SYNC=1        ; export VGL_SYNC     ;;
	-sy*)       VGL_SYNC=0        ; export VGL_SYNC     ;;
	+sp*)       VGL_SPOIL=1       ; export VGL_SPOIL    ;;
	-sp*)       VGL_SPOIL=0       ; export VGL_SPOIL    ;;
	-sa*)       VGL_SUBSAMP=$2    ; export VGL_SUBSAMP  ; shift     ;;
	-s*)        VGL_SSL=0         ; export VGL_SSL      ;;
	+s*)        VGL_SSL=1         ; export VGL_SSL      ;;
	-pr*)       VGL_PROFILE=0     ; export VGL_PROFILE  ;;
	+pr*)       VGL_PROFILE=1     ; export VGL_PROFILE  ;;
	-q*)        VGL_QUAL=$2       ; export VGL_QUAL     ; shift     ;;
	+de*)       VGL_DEBUG=1       ; export VGL_DEBUG    ;;
	-de*)       VGL_DEBUG=0       ; export VGL_DEBUG    ;;
	+tr*)       VGL_TRACE=1       ; export VGL_TRACE    ;;
	-tr*)       VGL_TRACE=0       ; export VGL_TRACE    ;;
	-d*)        VGL_DISPLAY=$2    ; export VGL_DISPLAY  ; shift     ;;
	-cl*)       VGL_CLIENT=$2     ; export VGL_CLIENT   ; shift     ;;
	-p*)        VGL_PORT=$2       ; export VGL_PORT     ; shift     ;;
	-c*)        VGL_COMPRESS=$2   ; export VGL_COMPRESS ; shift     ;;
	-np*)       VGL_NPROCS=$2     ; export VGL_NPROCS   ; shift     ;;
	-g*)        VGL_GAMMA=0       ; export VGL_GAMMA    ;;
	+g*)        VGL_GAMMA=1       ; export VGL_GAMMA    ;;
	-v*)        VGL_VERBOSE=0     : export VGL_VERBOSE  ;;
	+v*)        VGL_VERBOSE=1     : export VGL_VERBOSE  ;;
	-ld)        LD_LIBRARY_PATH=$1:$LD_LIBRARY_PATH ;
	            export LD_LIBRARY_PATH              ; shift     ;;
	-64)        __VGL_64=1        ;;
	-32)        __VGL_32=1        ;;
	-h)         usage 0 ;;
	--help)     usage 0 ;;
	--)         shift   ; break ;;
	-*)         usage 1 ;;
	*)          break   ;;
	esac
	shift
done

case `uname -s` in

SunOS)

if [ -z "$FAKERLIB" ]; then
FAKERLIB=librrfaker.so
if [ -f /opt/SUNWvgl/lib/sparcv9/librrfaker.so ]
then
	FAKERLIB=/opt/SUNWvgl/lib/sparcv9/librrfaker.so
fi
if [ -f /opt/SUNWvgl/lib/64/librrfaker.so ]
then
	FAKERLIB=/opt/SUNWvgl/lib/64/librrfaker.so
fi
fi
if [ -z "$FAKERLIB32" ]; then
FAKERLIB32=librrfaker.so
if [ -f /opt/SUNWvgl/lib/librrfaker.so ]
then
	FAKERLIB32=/opt/SUNWvgl/lib/librrfaker.so
fi
fi
if [ -z "$__VGL_64" ]; then
	LD_PRELOAD_32=$FAKERLIB32
	export LD_PRELOAD_32
fi
if [ -z "$__VGL_32" ]; then
	LD_PRELOAD_64=$FAKERLIB
	export LD_PRELOAD_64
fi
exec ${1+"$@"}

;;

*)

LD_PRELOAD=librrfaker.so
export LD_PRELOAD
exec ${1+"$@"}

;;

esac
