#!/bin/sh

uid() {
    id | cut -f2 -d = | cut -f1 -d \(;
}

_XINIT=/etc/X11/xinit/xinitrc.d/vglclient.sh
_XINITRC=/etc/X11/xinit/xinitrc
_DAEMON=/usr/bin/vglclient_daemon
_POSTSESSION=/etc/X11/gdm/PostSession/Default

# SuSE
if [ -f /etc/opt/gnome/gdm/PostSession/Default ]; then
    _POSTSESSION=/etc/opt/gnome/gdm/PostSession/Default
fi

WHICH0=`which $0`
BINDIR=`dirname $WHICH0`

case "$1" in

-install)
		if [ ! `uid` -eq 0 ]; then echo Only root can do that!; exit 1; fi
		if [ ! -f $_POSTSESSION ]; then echo Not supported on this platform; exit 1; fi
		if [ -d /etc/X11/xinit/xinitrc.d ]; then
			echo $_DAEMON start >$_XINIT
			chmod 755 $_XINIT
		else
			if [ -f /etc/X11/xinit/xinitrc ]; then
				perl -i -p -e "s:$_DAEMON start\n::g;" $_XINITRC
				echo -e "1a\n$_DAEMON start\n.\nwq" | ed $_XINITRC
			else
				echo Not supported on this platform; exit 1;
			fi
		fi
		if [ -f $_POSTSESSION ]; then
			perl -i -p -e "s:$_DAEMON stop\n::g;" $_POSTSESSION
			echo -e "1a\n$_DAEMON stop\n.\nwq" | ed $_POSTSESSION
		fi
		echo Done!  Restart your X session to activate.
		exit 0
		;;
-remove)
		if [ ! `uid` -eq 0 ]; then echo Only root can do that!; exit 1; fi
		if [ ! -f $_POSTSESSION ]; then echo Not supported on this platform; exit 1; fi
		if [ -d /etc/X11/xinit/xinitrc.d ]; then
			if [ -f $_XINIT ]; then rm $_XINIT; fi
		else
			if [ -f /etc/X11/xinit/xinitrc ]; then
				perl -i -p -e "s:$_DAEMON start\n::g;" $_XINITRC
			else
				echo Not supported on this platform; exit 1;
			fi
		fi
		if [ -f $_POSTSESSION ]; then
			perl -i -p -e "s:$_DAEMON stop\n::g;" $_POSTSESSION
		fi
		exit 0
		;;
*)
		echo USAGE: $0 \< -install \| -remove \>
		;;

esac
