#!/bin/sh

uid() {
    id | cut -f2 -d = | cut -f1 -d \(;
}

_XINIT=/etc/X11/xinit/xinitrc.d/vglclient.sh
_XINITSSL=/etc/X11/xinit/xinitrc.d/vglclient_ssl.sh
_DAEMON=/usr/bin/vglclient_daemon
_DAEMONSSL=/usr/bin/vglclient_ssldaemon
_POSTSESSION=/etc/X11/gdm/PostSession/Default

WHICH0=`which $0`
BINDIR=`dirname $WHICH0`

while [ 1 ]
do
	echo
	echo "1) Install VirtualGL Client as a Service"
	echo "2) Install VirtualGL Secure Client as a Service"
	echo "3) Remove VirtualGL Client Service"
	echo "4) Remove VirtualGL Secure Client Service"
	echo "X) Exit"
	echo
	echo Choose:
	read _CHOICE

	case $_CHOICE in
	1) if [ ! `uid` -eq 0 ]; then echo Only root can do that!; continue; fi
		if [ ! -d /etc/X11/xinit/xinitrc.d ]; then echo Not supported on this platform; continue; fi
		if [ ! -e $_POSTSESSION ]; then echo Not supported on this platform; continue; fi
		echo $_DAEMON start >$_XINIT
		chmod 755 $_XINIT
		if [ -x $_POSTSESSION ]; then
			perl -i -p -e "s:$_DAEMON stop\n::g;" $_POSTSESSION
			echo -e "1a\n$_DAEMON stop\n.\nwq" | ed $_POSTSESSION
		fi
		echo Done!  Restart your X session to activate.
		continue
		;;
	2) if [ ! `uid` -eq 0 ]; then echo Only root can do that!; continue; fi
		if [ ! -d /etc/X11/xinit/xinitrc.d ]; then echo Not supported on this platform; continue; fi
		if [ ! -e $_POSTSESSION ]; then echo Not supported on this platform; continue; fi
		echo $_DAEMONSSL start >$_XINITSSL
		chmod 755 $_XINITSSL
		if [ -x $_POSTSESSION ]; then
			perl -i -p -e "s:$_DAEMONSSL stop\n::g;" $_POSTSESSION
			echo -e "1a\n$_DAEMONSSL stop\n.\nwq" | ed $_POSTSESSION
		fi
		echo Done!  Restart your X session to activate.
		continue
		;;
	3) if [ ! `uid` -eq 0 ]; then echo Only root can do that!; continue; fi
		if [ ! -d /etc/X11/xinit/xinitrc.d ]; then echo Not supported on this platform; continue; fi
		if [ ! -e $_POSTSESSION ]; then echo Not supported on this platform; continue; fi
		if [ -x $_XINIT ]; then rm $_XINIT; fi
		if [ -x $_POSTSESSION ]; then
			perl -i -p -e "s:$_DAEMON stop\n::g;" $_POSTSESSION
		fi
		continue
		;;
	4) if [ ! `uid` -eq 0 ]; then echo Only root can do that!; continue; fi
		if [ ! -d /etc/X11/xinit/xinitrc.d ]; then echo Not supported on this platform; continue; fi
		if [ ! -e $_POSTSESSION ]; then echo Not supported on this platform; continue; fi
		if [ -x $_XINITSSL ]; then rm $_XINITSSL; fi
		if [ -x $_POSTSESSION ]; then
			perl -i -p -e "s:$_DAEMONSSL stop\n::g;" $_POSTSESSION
		fi
		continue
		;;
	X) break
		;;
	x) break
		;;
	    esac
done
